language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls portalocker
    - pip install scipy
    - pip install numpy
script:
    - py.test
after_success:
    - coveralls
